### PR TITLE
fix lcov format

### LINKED ISSUE #25: Cloverage should return a non zero exit code when tests fail

### LINKED ISSUE #225: Invalid lcov format?
Hi 👋 !

My team recently started using CodeClimate - and I was happy to discover that we can use its coverage reporting via lcov format. Here's the setup (assumes that everything is configured on CodeClimate side):

https://github.com/lukaszkorecki/codeclimate-kibit/blob/73491d0a1d280a35ef4d1496d1e93cd2fb9de911/.circleci/config.yml#L43-L48

```bash
./cc-test-reporter before-build
lein trampoline cloverage --lcov --no-text --no-html --no-summary -o $PWD
testRes=$?
mkdir -p coverage
sed 's/^SF:/SF:src\//' lcov.info > coverage/lcov.info
./cc-test-reporter after-build --coverage-input-type lcov --exit-code $testRes 
```

The line with `sed` invokation addresses the issue I found. Generated lcov report doesn't include the `src/` part of the path to the files found during test run:

```
$ grep SF: lcov.info
SF:codeclimate/reporter.clj
SF:codeclimate/ignore.clj
SF:codeclimate/kibit.clj
```

I'm not really familiar with lcov format, but it looks like it's a bug - given that the coverage report runs from the root of the project, I'd expect the paths in the coverage report to be also relative to the root.

If it's a real issue I'm more than happy to fix this 👍 or add a command line flag to optionally add a prefix to paths generated in lcov format.

### PR DESCRIPTION
**Pull request by thumbnail**
fixes #225 

uploading to codeclimate verified locally as well.

### CODE REVIEW

**Comment by lennartbuit** [comment]
Hai, I am a coworker of @thumbnail who asked for a review before submitting a patch, so thats why I commented on the diff ^^!

**Comment by thumbnail** [comment]
I noticed the build fails on openjdk 9 (as it does on master). i assume it's unrelated.

other builds are green tho 💚

File: cloverage/src/cloverage/source.clj [hunk 1]
```diff
@@ -1,10 +1,13 @@
...
             [clojure.tools.reader.reader-types :as rt]
-            [clojure.java.io :as io]))
+            [clojure.java.io :as io]
+            [clojure.string :as str])
+  (:import (java.io InputStreamReader File PushbackReader)
+           (clojure.lang RT)))
 
 (defn- get-loader ^ClassLoader []
-  (clojure.lang.RT/baseLoader))
+  (RT/baseLoader))
```
Comment (lvh) [inline cloverage/src/cloverage/source.clj]: Wait, what does this change do? Isn't clojure.lang already always available?

**Comment by lvh** [comment]
This change mostly looks fine to me, I'm just confused about the import change :)

#25 is a ticket about error codes; do you mean fixes #225?

**Comment by lvh** [comment]
Per commit: #255 so I'm guessing you mean #225 because #255 doesn't exist yet :D (Just noting that we need to manually close that ticket once this merges.)

**Comment by thumbnail** [comment]
> #25 is a ticket about error codes; do you mean fixes #225?
Yes i did an oopsie; changed the PR description so if you merge this it should be fine :)

File: cloverage/src/cloverage/source.clj (hunk 1 above)
Comment (thumbnail) [reply cloverage/src/cloverage/source.clj]: I moved the import to the top so you don't have to fully quantify the path, see https://clojuredocs.org/clojure.core/import :)

**Comment by lvh** [comment]
You mean #225? :grimacing: :smile:

File: cloverage/src/cloverage/source.clj (hunk 1 above)
Comment (lvh) [reply cloverage/src/cloverage/source.clj]: Sure, sure -- I understand `:import`, just checking that there isn't some weird side effect that you need this for since AFAICT cloverage is mostly just a mechanism for finding weird edge cases about Clojure's dependency management :)

**Comment by thumbnail** [comment]
Hahaha, its a very confusing number 😁
