### PR TITLE
Fix instrumenting inlined function calls & performance improvements

### LINKED ISSUE #277: Instrumenting inlined primitive cast functions like int() can cause some instrumentation to fail
I mentioned this in #257 -- part of the reason it was failing was instrumenting the methods ultimately generated by `defrecord` fails with a "Must assign primitive to primitive mutable". #273 worked around this by not instrumenting the methods automatically generated by `defrecord`, but the underlying problem is still there.

`defrecord` ultimiately generates a method that is something like this:

```clj
(deftype MyType [^:unsynchronized-mutable ^int i]
  clojure.lang.IHashEq
  (hasheq [_]
    (set! i (int 2))))
```

Attemtping to instrument this causes the "Must assign primitive" error:

```clj
(defn instrument [form]
  (inst/instrument-form #'inst/no-instr nil form))
    
(deftype MyType [^:unsynchronized-mutable ^int i]
  clojure.lang.IHashEq
  (hasheq [_]
    (set! i (instrument (int 2)))))
;; -> Must assign primitive to primitive mutable: i
```

I think the correct fix here is not to instrument primitive inline initializers like `int` at all, or at least not instrument the `(int ...)` form itself (instrumenting its arg is probably fine).

I'm planning on tackling this issue today

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #277

Certain function calls like `clojure.core/+` are replaced with inlined versions by the compiler or by Riddley when macroexpanding (this is not necessarily true of all arities):

```clj
(rw/macroexpand '(+ 1 2))
;; -> (. clojure.lang.Numbers (add 1 2))

(rw/macroexpand '(+ 1))
;; -> (+ 1)
```

Previously Cloverage would not expand the inlined function calls during instrumentation, which would lead to errors evaluating the instrumented form -- see #277 for an example/ This PR tweaks Cloverage so it correctly expands inlined calls before instrumentation so the resulting form matches the behavior of the compiler.

I had to rework `instrument/list-type` a bit to get this working and while I was at it I made some tweaks that resulting in a 5x performance increase in that function. Since it is used for every single form in the project this should result in a nice perf increase for instrumentation. I tested this change with Metabase (322 namespaces) and it shaves almost a whole second off of the time it takes to instrument the entire project (29.4 seconds before the change; 28.7 seconds after).

### CODE REVIEW

File: cloverage/src/cloverage/instrument.clj [hunk 1]
```diff
@@ -1,18 +1,19 @@
...
+            [clojure.tools.logging :as log]
             [clojure.tools.reader :as r]
             [cloverage.debug :as d]
             [cloverage.rewrite :refer [unchunk]]
             [cloverage.source :as s]
             [riddley.walk :as rw]
             [slingshot.slingshot :refer [throw+]]))
 
-(defn iobj? [form]
+(defn- iobj? [form]
```
Comment (camsaul) [inline cloverage/src/cloverage/instrument.clj:11]: There are a bunch of functions used only in this namespace. I made them private so it's easier to refactor this namespace going forward -- this way we don't need to try to work out if they're used anywhere else.

File: cloverage/src/cloverage/instrument.clj [hunk 2]
```diff
@@ -31,16 +32,29 @@
...
+  inlined version."
+  [[head & args]]
+  (when (symbol? head)
+    (when-let [{:keys [inline inline-arities]} (meta (resolve head))]
+      (when inline
+        ;; some inlineable function calls such as to `+` are only replaced with the inlined version for certain arities
+        ;; -- the `:inline-arities` function in the metadata can be used to check whether the call will be inlined
+        (if inline-arities
+          (inline-arities (count args))
+          true)))))
```
Comment (camsaul) [inline cloverage/src/cloverage/instrument.clj:56]: To determine whether a list is a function call that will be replaced with the inlined version we have to look at the whole form rather than just the symbol at the head of the list

File: cloverage/src/cloverage/instrument.clj [hunk 3]
```diff
@@ -79,59 +93,79 @@
...
+           (special-symbol? head)   :unknown
+           :else                    :list))))
+
+  ([[head :as form] env]
+   ;; if the list is a call to a symbol with a local binding, but not a special form such as `var` or `new` (which
+   ;; aren't overshadowed by local variables) return `:list` type.
+   (if (and (get env head)
+            (not (special-symbol? head)))
+     :list
+     (list-type form))))
```
Comment (camsaul) [inline cloverage/src/cloverage/instrument.clj:158]: Because `inlined-fn-call?` needs to look at the whole form I had to rework `list-type` to take the whole form instead of just the form at its head. As part of that I converted replaced the long `condp` call with a map of symbol -> type that speeds instrumentation up quite a bit.

File: cloverage/src/cloverage/instrument.clj [hunk 4]
```diff
@@ -517,18 +551,20 @@
...
+      ;; form, so we can continue
       (catch Throwable e
-        (log/error "Error instrumenting form"
-                   (ex-info "Error instrumenting form" {:filename filename
-                                                        :line     line-hint
-                                                        :form     form}
-                            e))
+        (log/error (.getMessage e) "\n"
+                   (binding [*print-meta* true]
+                     (with-out-str (pprint/pprint (Throwable->map e)))))
```
Comment (camsaul) [inline cloverage/src/cloverage/instrument.clj:567]: While trying to work out the root cause of the bug I wanted to fix I made some tweaks to the errors that get logged which makes debugging errors a lot easier. By pretty-printing the map representation of the whole Exception chain it's easier to see the root cause of the failure as well as the various instrumented/macroexpanded forms involved (including metadata)

File: cloverage/src/cloverage/sample/exercise_instrumentation.clj [hunk 5]
```diff
@@ -5,8 +5,12 @@
 
 '()
 
+(+ 40)
+
 (+ 40 2)
 
+(str 1 2 3)
+
```
Comment (camsaul) [inline cloverage/src/cloverage/sample/exercise_instrumentation.clj:13]: Because `(+ 40 2)` actually gets replaced with an inlined function call by the compiler I added some more forms that don't get replaced so we can test for those as well.

File: cloverage/test/cloverage/coverage_test.clj [hunk 6]
```diff
@@ -81,9 +81,8 @@
                    wrapped))))
 
 (t/deftest test-wrap-list
-  (t/is (expand= `(cov/capture 0 ((cov/capture 1 +) (cov/capture 2 1)
-                                                    (cov/capture 3 2)))
-                 (inst/wrap #'cov/track-coverage 0 `(+ 1 2)))))
+  (t/is (expand= `(cov/capture 0 ((cov/capture 1 my-fn) (cov/capture 2 1) (cov/capture 3 2)))
+                 (inst/wrap #'cov/track-coverage 0 `(my-fn 1 2)))))
```
Comment (camsaul) [inline cloverage/test/cloverage/coverage_test.clj:85]: Tweaked because the instrumented version of `(+ 1 2)` is no longer `((capture ... +) (capture ... 1) (capture ... 2))`

File: cloverage/test/cloverage/coverage_test.clj [hunk 7]
```diff
@@ -197,15 +196,15 @@
...
-    (t/is (find-form cov '(inc (m c 0))))))
+  (let [cov @cov/*covered*]
+    (doseq [[form expanded] '{(+ 40)      (+ 40)
+                              (+ 40 2)    (. clojure.lang.Numbers (add 40 2))
+                              (str 1 2 3) (str 1 2 3)
+                              (inc m c 0) (. clojure.lang.Numbers (inc (m c 0)))}]
+      (t/testing (format "Form %s (expanded to %s) should get instrumented" (pr-str form) (pr-str expanded))
+        (t/is (find-form cov expanded))
+        (let [found (find-form cov expanded)]
+          (t/is (:line found)))))))
```
Comment (camsaul) [inline cloverage/test/cloverage/coverage_test.clj:207]: Reworked this test to use `doseq` so we can include `testing` context info in there to make it easier to distinguish failures for the various forms. I kept the original two forms tested here (both of which are now correctly expanded to inlined versions) and added a couple more that aren't expanded

File: cloverage/test/cloverage/instrument_test.clj [hunk 8]
```diff
@@ -37,17 +32,46 @@
...
+           {['((or + 1) 1 2)] :list}
+
+           "List-like classes e.g. clojure.lang.Cons for which `list?` is false"
+           {[(cons 1 '(2 3))] :list}}
+
+          [[form env] expected] form->expected]
+    (t/testing message
+      (t/testing (str "\n" (pr-str (list 'form-type form env)))
+        (t/is (= expected
+                 (inst/form-type form env)))))))
```
Comment (camsaul) [inline cloverage/test/cloverage/instrument_test.clj:74]: Reworked this test so it uses `doseq` and adds `testing` context so it's easier to understand which form failed. Added new tests for `:inlined-fn-call` and some other stuff that was missing like lists starting with other lists

File: cloverage/src/cloverage/instrument.clj [hunk 9]
```diff
@@ -79,59 +93,79 @@
...
+                  `#{defmulti}    :defmulti ; special case defmulti to avoid boilerplate
+                  `#{defprotocol} :atomic   ; no code in protocols
+                  `#{defrecord}   :record
+                  `#{deftype*}    :deftype*
+                  `#{ns}          :atomic
+
+                  ;; http://dev.clojure.org/jira/browse/CLJ-1330 means AOT-compiled definlines
+                  ;; are broken when used indirectly. Work around - do not wrap the definline
+                  `#{booleans bytes chars shorts floats ints doubles longs} :definlined-fn-call}
+                 symb symbols]
```
Comment (camsaul) [inline cloverage/src/cloverage/instrument.clj:130]: The fix in this PR mainly concerns functions defined with `defn` but with `:inline` metadata such as `+` or `int`. Cloverage previously had a special case for functions defined with `definline` such as `booleans` or `bytes`. For these existing special cases, I did not change the behavior, but to make the difference between the two situations clearer I renamed the `:inline` form type to `:defininlined-fn-call` and added `:inlined-fn-call` for the forms fixed in this PR.

File: cloverage/test/cloverage/instrument_test.clj [hunk 10]
```diff
@@ -217,10 +241,32 @@
           (let [[[message-type _ message]] @log-messages]
             (t/is (= :error
                      message-type))
-            (doseq [s ["Error instrumenting form"
+            (doseq [s ["Error evaluating instrumented form"
```
Comment (camsaul) [inline cloverage/test/cloverage/instrument_test.clj:244]: The reworked error-handling code now differentiates between an error that happens during instrumentation and an error that happens while evaluating the instrumented form, so I had to update this test.

File: .travis.yml [hunk 11]
```diff
@@ -19,6 +19,7 @@ before_script:
                 eastwood "{:exclude-namespaces [cloverage.sample.exercise-instrumentation]}", \
                 eastwood "{:namespaces [cloverage.sample.exercise-instrumentation] \
                            :exclude-linters [:unused-ret-vals \
+                                             :suspicious-expression \
```
Comment (camsaul) [inline .travis.yml:22]: Eastwood was complaining about the `(+ 1)` forms I added to `cloverage.sample.exercise-instrumentation` for the tests

File: .gitignore [hunk 12]
```diff
@@ -15,3 +15,4 @@ pom.xml*
 */.nrepl-port
 .idea/
 cloverage.iml
+.eastwood
```
Comment (camsaul) [inline .gitignore:18]: Running Eastwood locally generates this file; don't need/want to have it in CI

File: cloverage/src/cloverage/instrument.clj [hunk 13]
```diff
@@ -244,9 +278,15 @@
...
 ;; Don't wrap definline functions - see http://dev.clojure.org/jira/browse/CLJ-1330
-(defmethod do-wrap :inlined [f line [inline-fn & body] _]
+(defmethod do-wrap :definlined-fn-call [f line [inline-fn & body] _]
   `(~inline-fn ~@(map (wrapper f line) body)))
 
+;; Other functions that are defined via `defn` but that define special `:inline` versions in their metadata, such as
+;; `clojure.core/int`, should get expanded to the inlined versions before instrumentation. Riddley can expand it for
+;; us
+(defmethod do-wrap :inlined-fn-call [f line form _]
+  (f line (rw/macroexpand form)))
```
Comment (camsaul) [inline cloverage/src/cloverage/instrument.clj:288]: Actually this should probably be `(wrap f line (rw/macroexpand form))`

File: cloverage/src/cloverage/instrument.clj (hunk 9 above)
Comment (lvh) [reply cloverage/src/cloverage/instrument.clj:129]: I appreciate this comment, it made it much easier to follow what was going on.

**Comment by lvh** [comment]
I've started reviewing this and the general direction looks good, but those test failures look real.

**Comment by camsaul** [comment]
Right, I'm working on fixing the test failures right now. I ended up uncovering a bug in Riddley: https://github.com/ztellman/riddley/issues/33

I came up with a way to work around it in but then I ran into #305 so I'm looking to see if I can fix that as part of this PR

File: cloverage/src/cloverage/coverage.clj [hunk 14]
```diff
@@ -164,17 +164,21 @@
...
+        (if nop?
+          (inst/instrument #'inst/nop namespace)
+          (inst/instrument #'track-coverage namespace)))
+      (println "Instrumented" namespace)
+      ;; mark the ns as loaded
+      (mark-loaded namespace))
+    (printf "Instrumented %d namespaces in %.1f seconds.\n"
+            (count ordered-nses)
+            (/ (- (System/currentTimeMillis) start-time-ms)
+               1000.0))))
```
Comment (camsaul) [inline cloverage/src/cloverage/coverage.clj:181]: The only change here is to record how long instrumentation takes and log that. Used this to measure the impact of the performance increase but it seemed useful so I left it in.

File: cloverage/src/cloverage/instrument.clj [hunk 15]
```diff
@@ -459,18 +505,6 @@
...
-  "Return a sequence of all forms in a source file using `source-reader` to read them."
-  [source-reader]
-  ;; `read-form` will return `nil` at the end of the file so keep reading forms until we run out
-  (letfn [(read-form []
-            (binding [*read-eval* false]
-              (r/read {:eof       nil
-                       :features  #{:clj}
-                       :read-cond :allow}
-                      source-reader)))]
-    (take-while some? (repeatedly read-form))))
```
Comment (camsaul) [inline cloverage/src/cloverage/instrument.clj:472]: Moved this functionality to the `source` namespace

File: cloverage/src/cloverage/instrument.clj [hunk 16]
```diff
@@ -517,43 +546,48 @@
...
+
+    (f line-hint form) -> instrumented-form"
+
+  [f-var ns-symbol]
+  (let [filename (source/resource-path ns-symbol)]
     (try
-      (let [instrumented (instrument-file f-var lib filename)]
-        (d/dump-instrumented instrumented lib)
+      (let [instrumented (instrument-file f-var ns-symbol filename)]
+        (d/dump-instrumented instrumented ns-symbol)
```
Comment (camsaul) [inline cloverage/src/cloverage/instrument.clj:585]: Personally I found the name `lib` confusing -- it actually refers to a symbol naming a namespace, but that's not obvious. Elsewhere the codebase uses `ns-symbol` so I changed the code here to use that for consistency.

File: cloverage/src/cloverage/instrument.clj [hunk 17]
```diff
@@ -332,19 +377,20 @@
...
-  (if (= :list (form-type attr-name env))
-    (do
-      (d/tprnl "List dotform, recursing on" (rest attr-name))
-      (f line `(~dot-sym ~obj-name (~(first attr-name)
-                                    ~@(doall (map (wrapper f line)
-                                                  (rest attr-name)))))))
-    (do
-      (d/tprnl "Simple dotform, recursing on" args)
-      (f line `(~dot-sym ~obj-name ~attr-name ~@(doall (map (wrapper f line) args)))))))
+  (if (seq? (first more))
```
Comment (camsaul) [inline cloverage/src/cloverage/instrument.clj:385]: #305 was caused by trying to determine the `form-type` of the java interop form. The intention here is to see whether we're using the `(. obj method & args)` or `(. obj (method & args))` syntax, but `form-type` could return something other than `:list` depending on what the method name was.

Using `seq?` here is sufficient.

**Comment by lvh** [comment]
Sweet--tests passing :) Anything you want to polish before review or am I good to read this over?

**Comment by camsaul** [comment]
@lvh everything is good to go and ready for review. I tested everything locally with a few different projects and things look good and this PR definitely fixes a few issues.

File: cloverage/test/cloverage/coverage_test.clj [hunk 18]
```diff
@@ -197,15 +199,21 @@
...
+                                                                        cloverage.coverage/track-coverage 10 2)))
+                              (str 1 2 3) (str 1 2 3)
+                              (inc m c 0) (. clojure.lang.Numbers (inc (cloverage.instrument/wrapm
+                                                                        cloverage.coverage/track-coverage
+                                                                        101
+                                                                        (m c 0))))}]
+      (t/testing (format "Form %s (expanded to %s) should get instrumented" (pr-str form) (pr-str expanded))
+        (t/is (find-form cov expanded))
+        (let [found (find-form cov expanded)]
+          (t/is (:line found)))))))
```
Comment (camsaul) [inline cloverage/test/cloverage/coverage_test.clj:216]: Since `(+ 40 2)` is actually replaced with the inlined version now I had to rework this test. I kept the original two forms being checked and added a few more that aren't replaced with inlined versions. I put them all in a `doseq` form so I could add `testing` context which makes it a lot easier to understand which assertions are failing when the test fails

File: cloverage/test/cloverage/instrument_test.clj [hunk 19]
```diff
@@ -217,10 +241,63 @@
...
+(t/deftest instrument-java-interop-forms-test
+  (t/testing "Java interop forms should get instrumented correctly (#304)"
+    (t/testing "Method calls"
+      ;; these two syntaxes are equivalent
+      (t/testing "(. object method & args) syntax"
+        (t/is (= '(do (. clojure.lang.RT count (do [(do 3) (do 4)])))
+                 (rw/macroexpand-all (inst/instrument-form #'inst/nop nil '(. clojure.lang.RT count [3 4]))))))
+      (t/testing "(. object (method & args)) syntax"
+        (t/is (= '(do (. clojure.lang.RT (count (do [(do 3) (do 4)]))))
+                 (rw/macroexpand-all (inst/instrument-form #'inst/nop nil '(. clojure.lang.RT (count [3 4]))))))))))
```
Comment (camsaul) [inline cloverage/test/cloverage/instrument_test.clj:261]: This is a test for #305 which I think actually only was an issue in this PR. There were previously no tests for the Java interop forms here so I thought it was a good idea to add some

File: cloverage/test/cloverage/source_test.clj [hunk 20]
```diff
@@ -18,9 +18,10 @@
 
 (t/deftest multibyte-test
   (t/testing "Form reader reads files with multibyte chars"
-    (t/is (= (source/forms 'cloverage.sample.multibyte-sample)
-             '((ns cloverage.sample.multibyte-sample)
-               (def a "あ"))))))
+    (t/is (= '((ns cloverage.sample.multibyte-sample)
+               (def a "あ"))
+             (with-open [reader (source/form-reader 'cloverage.sample.multibyte-sample)]
+               (vec (source/forms reader)))))))
```
Comment (camsaul) [inline cloverage/test/cloverage/source_test.clj:24]: The old `source/forms` function was only used by this test (and nowhere else); there was a different `instrument/source-forms` function in the instrumentation namespace. I consolidated both into a new `source/forms` function based on `instrument/source-forms`. I think a source forms function belongs in `source/` and not `instrument/` anyway. I've reworked this test to test the new version of the function.
