### PR TITLE
Fix instrumenting generated defrecord forms

### LINKED ISSUE #257: Bug with deftype
Yesterday we had a bit of a surprise when test coverage stopped working.

First because it was working fine on Friday and on the same commit it was failing the Monday after.
This turns out was just because:
- a new version of cloverage came out the 6th of October
- we had pinned the version of "lein-cloverage" but not cloverage the library

This meant that "cloverage" auto updated and we hit a bug with the `deftype*` instrumentation.

So I guess that ideally "lein-cloverage" should pin its own corresponding "cloverage" version to avoid these kind of surprises in the future?

The actual error with version 1.1.2 is attached below.
I can also provide a sample failing form if it's useful, what's the best way to help?

```
Caused by: Syntax error compiling deftype* at _(our_code.clj:1:198)._
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7114)
	at clojure.lang.Compiler.analyze(Compiler.java:6789)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7094)
	at clojure.lang.Compiler.analyze(Compiler.java:6789)
	at clojure.lang.Compiler.analyze(Compiler.java:6745)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6118)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6436)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7106)
	at clojure.lang.Compiler.analyze(Compiler.java:6789)
	at clojure.lang.Compiler.analyze(Compiler.java:6745)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6120)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5467)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4029)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7104)
	at clojure.lang.Compiler.analyze(Compiler.java:6789)
	at clojure.lang.Compiler.eval(Compiler.java:7173)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.eval(Compiler.java:7131)
	at clojure.core$eval.invokeStatic(core.clj:3214)
	at clojure.core$eval.invoke(core.clj:3210)
	at cloverage.instrument$instrument$fn__52271$fn__52272.invoke(instrument.clj:460)
	at cloverage.instrument$instrument$fn__52271.invoke(instrument.clj:458)
	... 25 more
Caused by: java.lang.IllegalArgumentException: Must assign primitive to primitive mutable: __hasheq
```

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #257 and #271. Confirmed working with the test project from #271. 

The core issue was that unknown macros like `defrecord+` we getting fully macroexpanded to `deftype*` forms before instrumentation was attempted. I tweaked the `do-wrap` implementation for `:list` to macroexpand one step at a time and then attempt instrumentation. 

I also fixed `do-wrap` for `:do` as part of this fix. I'm not entirely clear on why this is yet, but mapping `(wrapper f line)` does not recursively instrument forms the same way mapping `do-wrap` does. Without the changes to `:do`, macros like `defrecord+` would work correctly but not if they were inside a `do` form.

This is probably an issue with `wrapper` in general, so that itself is worth further investigation

### CODE REVIEW

File: cloverage/src/cloverage/instrument.clj [hunk 1]
```diff
@@ -400,13 +404,14 @@
...
-(defmethod do-wrap :record [f line [defr-symbol name fields & opts+specs] _]
+(defmethod do-wrap :record
+  [f line [defr-symbol name fields & opts+specs] _]
   ;; (defrecord name [fields*] options* specs*)
   ;;
   ;; spec == thing-being-implemented (methodName [args*] body)*
   ;; we only want to recurse on the methods
   (let [wrapped-opts+specs (for [opt-or-spec opts+specs]
-                             (if (list? opt-or-spec)
+                             (if (seq? opt-or-spec)
```
Comment (camsaul) [inline cloverage/src/cloverage/instrument.clj:414]: `defmacro` forms usually expand into `clojure.lang.Cons` which isn't a `list?`

**Comment by lvh** [comment]
Sweet! Thanks :) And sorry about cljfmt :)
