### PR TITLE
Fix Java interop forms for static method calls directly on class

### LINKED ISSUE #309: Java interop forms calling static method on class are instrumented incorrectly
A dot-java interop form like

```clj
(list '. clojure.lang.RT 'nth [:a :b] 0 nil)
```

where `clojure.lang.RT` is a *class*, not the symbol `'clojure.lang.RT`, gets instrumented incorrectly like

```clj
(do (. (do clojure.lang.RT) 'nth (do [:a :b]) (do 0) (do nil))
```

which results in the Exception 

```
 java.lang.IllegalArgumentException: No matching method nth found taking 3 args for class java.lang.Class
```

This is a regression introduced by #307 (previously the class-or-instance part of the interop call wasn't instrumented at all)

In most normal circumstances for Java interop forms representing static method calls we'll see the symbol name of the class rather than the class itself since we're instrumenting the form before it gets evaluated; in certain cases however other macros may expand to forms that include the actual class -- this is the case with certain `core.async` macros

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #309

### CODE REVIEW

File: cloverage/test/cloverage/instrument_test.clj [hunk 1]
```diff
@@ -267,46 +267,10 @@
...
                                                                                      (str "X is" x)
-                                                                                     (Thread/currentThread))))))))))
-
-(t/deftest instrument-inlined-primitives-test
-  (t/testing "Inline primitive cast functions like int() should be instrumented correctly (#277)"
-    (t/is (= '(. clojure.lang.RT (intCast 2))
-             (rw/macroexpand-all (inst/instrument-form #'inst/no-instr nil '(int 2)))
-             (rw/macroexpand-all (inst/instrument-form #'inst/no-instr nil `(int 2)))))
-    (t/testing "make sure example in #277 actually gets instrumented and doesn't fall back to returning the original form"
-      (let [form '(deftype MyType [^:unsynchronized-mutable ^int i]
```
Comment (lvh) [inline cloverage/test/cloverage/instrument_test.clj:278]: Wait, so, this test was.. wrong? I feel like there's a regression test in here we're losing, can you (briefly) convince me otherwise?

Comment (camsaul) [reply cloverage/test/cloverage/instrument_test.clj:278]: Sorry @lvh, I did not mean to delete that test at all. I'm not sure how I ended up doing that. Let me fix the PR

Comment (camsaul) [reply cloverage/test/cloverage/instrument_test.clj:278]: I think I must have done branched off an old version of master that didn't have those tests in there yet. Fixed

**Comment by lvh** [comment]
Looks good. If you could add a CHANGELOG entry, I'll merge it.
